# TokyoNight Day palette for tmux
set -g @bg "#e1e2e7"
set -g @fg "#3760bf"
set -g @yellow "#8c6c3e"
set -g @cyan "#007197"
set -g @darkblue "#c4c8da"
set -g @green "#587539"
set -g @orange "#b15c00"
set -g @violet "#7847bd"
set -g @magenta "#9854f1"
set -g @blue "#2e7de9"
set -g @red "#f52a65"
set -g @transparent "default"
