# TokyoNight Moon palette for tmux
set -g @bg "#222436"
set -g @fg "#c8d3f5"
set -g @yellow "#ffc777"
set -g @cyan "#86e1fc"
set -g @darkblue "#2f334d"
set -g @green "#c3e88d"
set -g @orange "#ff966c"
set -g @violet "#fca7ea"
set -g @magenta "#c099ff"
set -g @blue "#82aaff"
set -g @red "#ff757f"
set -g @transparent "default"
